# Generated by Django 4.1.3 on 2023-02-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='User',
        ),
    ]
